set_property SRC_FILE_INFO {cfile:C:/GitHub/ControlsResearch/SystemImplementation/OutputTesting/OutputTesting.srcs/constrs_1/imports/new/const.xdc rfile:../../../OutputTesting.srcs/constrs_1/imports/new/const.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L7 [get_ports L1t_inv0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K7 [get_ports L1b_inv0]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J2 [get_ports L1t_inv1]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports L1b_inv1]
